### ISSUE TITLE
Does not work on django > 3

### ISSUE THREAD

**Issue by parruc** [UniversitaDellaCalabria/django-form-builder#11]
Does not work anymore on django >= 3 because ugettext_lazy` was deprecated in v2.2 and no longer used in django v3+.

[ImportError: cannot import name ‘ugettext_lazy’ from ‘django.utils.translation’](https://forum.djangoproject.com/t/importerror-cannot-import-name-ugettext-lazy-from-django-utils-translation/10943)

Check your version of django’s documentation regarding lazy translation https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#lazy-translations

**Comment by francesco-filicetti** [comment]
Hi @parruc ,
thank you!
Do you want to make a pull request to fix it?

**Comment by francesco-filicetti** [comment]
solved here 0ffba4d06a1856754904625cce226e05c915f832
