### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by softMaina** [UniversitaDellaCalabria/django-form-builder#3]
I would like to suggest that you detail the documentation properly. This will be easier to go through the documentation than your code to get what is happening.
Thank you

**Comment by peppelinux** [comment]
Hi @softMaina, documentation should be updated and I think that an example project could also full the remaining gaps.

Unit tests Will do also the remaining part.
Thank you for feedback, We'll close this issue when these things Will be done in future releases. If you want to go deeper please do pull requests, on documentation rst files, We'll Be Happy to get your contributions

**Comment by peppelinux** [comment]
@softMaina 
here I added an example project:
https://github.com/UniversitaDellaCalabria/django-form-builder/tree/captcha/example

here you'll find a basic andd easy documentation on how to start:
https://django-form-builder.readthedocs.io/en/latest/usage/dynamic-forms/description.html

Other improvements will come, please give us your suggetions and your idea on these latest commits.

ps = also added CaPTCHA field :)

**Comment by softMaina** [comment]
@peppelinux  Thanks a lot
