### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by agajankush** [UniversitaDellaCalabria/django-form-builder#4]
I am unable to install the package using pip
Lot of dependencies not satisfied.
First it is complaining about cannot import get_signatures form 'filesig' and I have the latest version of fielsig==0.3

After removing the try catch I found out that we need to import it like this
![image](https://user-images.githubusercontent.com/16169801/79878436-6a136380-83bb-11ea-9e02-3231e5d7d9fd.png)

After this was done I am getting this error
![image](https://user-images.githubusercontent.com/16169801/79878505-81525100-83bb-11ea-99fd-418782ae2857.png)

Also Installed captcha manually to remove the captcha error

Can someone help me with all this dependencies please??

**Comment by peppelinux** [comment]
apt install poppler-utils

pdfsig should be a system executable

**Comment by peppelinux** [comment]
Hi @agajankush the next release will come with unit tests and Travis-CI, this will give us a better posture in terms of setup and continous integration.

I'll close this issue when this asset will be availble, meanwhile let us know if you fixed your setup.
Thank you

**Comment by peppelinux** [comment]
Hi @agajankush 
I coded an error os screen when pdfsig is not available in the environment.
Unit tests and also CI is configured now but probably, soon as possibile, we'll move to a pure python signature validation library.

thank you
