### ISSUE TITLE
Captcha replay attacks

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/django-form-builder#6]
Captcha payload must be extended with a timestamp that defines its validity.
Actually it's weak against replay attacks

**Comment by francesco-filicetti** [comment]
solved here https://github.com/UniversitaDellaCalabria/django-form-builder/commit/ae70d48f10b9a637bcb03ed48e8493979afb6fb3

**Comment by francesco-filicetti** [comment]
captcha auto-refresh here https://github.com/UniversitaDellaCalabria/django-form-builder/commit/1ef0606936ae58039bad213023655949837a057c
